---
# Sundry devtool installation

- name: install linux headers
  apt:
    name: linux-headers-{{ ansible_kernel }}
    state: latest
    update_cache: yes

#
# VirtualBox
#
- name: add virtualbox apt key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present

- name: add virtualbox debian repo
  apt_repository:
    repo: deb https://download.virtualbox.org/virtualbox/debian {{ ansible_lsb.codename }} contrib
    state: present

- name: install virtualbox
  apt:
    name: virtualbox-6.0
    state: latest
    update_cache: yes

# TODO download and install extension pack

- name: add user to vboxusers
  user:
    name: "{{ user_name }}"
    groups: vboxusers
    append: yes # OMG can't believe this isn't the default!

- name: install openjdk
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - openjdk-11-jdk
    - openjdk-11-doc

- name: download sdkman
  get_url:
    url: https://get.sdkman.io
    dest: /tmp/sdkman_script
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: install sdkman
  environment:
    SDKMAN_DIR: "/home/{{ user_name }}/.sdkman"
  command: /bin/bash /tmp/sdkman_script
  become: no

- name: fix sdkman permissions
  file:
    path: "/home/{{ user_name }}/.sdkman"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0755"
    recurse: true

- name: add vscode key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: add vscode deb repo
  apt_repository:
    repo: deb https://packages.microsoft.com/repos/vscode stable main
    state: present
    update_cache: yes

- name: install vscode
  apt:
    name: code
    state: latest
    update_cache: yes
