---
# Sundry devtool installation

- name: install linux headers
  apt:
    name: linux-headers-{{ ansible_kernel }}
    state: latest
    update_cache: yes

#
# VirtualBox tasks
#
- name: add virtualbox apt key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present

- name: add virtualbox debian repo
  apt_repository:
    repo: deb https://download.virtualbox.org/virtualbox/debian {{ ansible_lsb.codename }} contrib
    state: present

- name: install virtualbox
  apt:
    name: virtualbox-6.0
    state: latest
    update_cache: yes

# TODO download and install extension pack

- name: add kenneth to vboxusers
  user:
    name: kenneth
    groups: vboxusers
    append: yes # OMG can't believe this isn't the default!
