---
# xfce specific tasks

- name: emacs keybindings...you will like them
  command: xfconf-query -c xsettings -p /Gtk/KeyThemeName -s Emacs
  become_user: kenneth

- name: copy xmodmaprc file
  copy:
    src: xmodmaprc
    dest: /home/kenneth/.xmodmaprc
    owner: kenneth
    group: kenneth
    mode: 0755

- name: xfce autostart xmodmap destop file
  copy:
    src: xmodmap.desktop
    dest: /home/kenneth/.config/autostart/
    owner: kenneth
    group: kenneth
    mode: 0755

# base16 color schemes
- name: clone the base16 repo
  git:
    repo: git clone https://github.com/chriskempson/base16-shell.git 
    dest: /home/kenneth/.config/base16-shell
    update: no
  become: no
    
- name: configure base16 in .bashrc
  blockinfile:
    path: /home/kenneth/.bashrc
    block: |
      BASE16_SHELL="$HOME/.config/base16-shell/"
      [ -n "$PS1" ] && \
        [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
        eval "$("$BASE16_SHELL/profile_helper.sh")"

  become: no

- name: install base16 terminal preview
  pip:
    name: base16-shell-preview
    state: latest
    umask: "0022"
