---
# xfce specific tasks

- name: emacs keybindings...you will like them
  command: xfconf-query -c xsettings -p /Gtk/KeyThemeName -s Emacs
  become_user: kenneth

- name: copy xmodmaprc file
  copy:
    src: xmodmaprc
    dest: /home/kenneth/.xmodmaprc
    owner: kenneth
    group: kenneth
    mode: 0755

- name: xfce autostart xmodmap destop file
  copy:
    src: xmodmap.desktop
    dest: /home/kenneth/.config/autostart/
    owner: kenneth
    group: kenneth
    mode: 0755

# base16 color themes for the xfce terminal
- name: clone the base16 repo into /tmp
  git:
    repo: https://github.com/afg984/base16-xfce4-terminal.git
    dest: /tmp/base16

- name: copy base16 themes
  copy:
    src: /tmp/base16/colorschemes/
    dest: /home/kenneth/.local/share/xfce4/terminal/colorschemes/
    owner: kenneth
    group: kenneth
    mode: 0755

- name: base16 terminal preview
  pip:
    name: base16-shell-preview
    state: latest
    umask: "0022"
