---
# I/Kenneth keep my dotfiles at GitHub. Clone them and set up links here

- name: clone dotfiles repo
  git:
    repo: 'git@github.com:kpb/dotfiles.git'
    dest: "/home/{{ user_name }}/dev/dotfiles"
    update: no
  become: no

- name: symlink bash aliases
  file:
    src: "/home/{{ user_name }}/dev/dotfiles/bash/bash_aliases"
    dest: "/home/{{ user_name }}/.bash_aliases"
    state: link
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0755

- name: symlink emacs init files
  file:
    src: "/home/{{ user_name }}/dev/dotfiles/emacs.d"
    dest: "/home/{{ user_name }}/.emacs.d"
    state: link
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0755
