---
- hosts: 127.0.0.1
  connection: local
  become: yes
  roles:
    - role: basics
      tags:
        - basics
    - role: dotfiles
      tags:
        - dotfiles
        - upgrade
    - role: xfce
      tags:
        - xfce
    - role: multimedia
      tags:
        - multimedia
    - role: devtools
      tags:
        - devtools
    - role: ai-tools
      tags:
        - ai-tools
    - role: docker
      tags:
        - docker
