---
# install docker

- name: install docker prerequisites
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: install docker repo key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: add docker repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present

- name: install docker
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: run docker hello world for great profit
  command: docker run hello-world
  register: hello_world

- debug: var=hello_world.stdout_lines

- name: create docker group
  group:
    name: docker
    state: present

- name: add user to docker group
  user:
    name: "{{ user_name }}"
    groups: docker
    append: yes # OMG can't believe this isn't the default!

- name: start and enable docker systemd service
  systemd:
    name: docker
    enabled: yes
    daemon_reload: yes
    state: restarted

- name: pip install docker-compose
  pip:
    name: docker-compose
    state: latest
